#ident $Id$

# OS Part
# FreeBSD Section
CC = gcc
CFLAGS = -Wall -I$(LDAP_INC_DIR) $(CON_FILE) -DLINUX_PAM -DFREEBSD $(CDEFS) -fPIC
LD_FLAGS = -x --shared -rpath $(LDAP_LIB_DIR) -lcrypt -lresolv

include Make.defs

