#ident $Id$

# OS Part
CC = gcc
CFLAGS = -Wall -I$(LDAP_INC_DIR) -DSOLARIS -D__EXTENSIONS__ $(CDEFS) -fPIC
LD_FLAGS = -M mapfile -G -h $(LIBAUTHSH) -z text -Bsymbolic \
	-R$(LDAP_LIB_DIR) 

include Make.defs

